export const paths = {
	auth: {
		auth0: {
			callback: "/auth/auth0/callback",
			profile: "/auth/auth0/profile",
			signIn: "/auth/auth0/sign-in",
			signOut: "/auth/auth0/sign-out",
			signUp: "/auth/auth0/sign-up",
		},
		clerk: {
			signOut: "/auth/clerk/sign-out",
		},
		cognito: {
			callback: "/auth/cognito/callback",
			signIn: "/auth/cognito/sign-in",
			signOut: "/auth/cognito/sign-out",
		},
		custom: {
			profile: "/auth/custom/profile",
			resetPassword: "/auth/custom/reset-password",
			signIn: "/auth/custom/sign-in",
			signOut: "/auth/custom/sign-out",
			signUp: "/auth/custom/sign-up",
		},
		samples: {
			signIn: { centered: "/auth/samples/sign-in/centered", split: "/auth/samples/sign-in/split" },
			signUp: { centered: "/auth/samples/sign-up/centered", split: "/auth/samples/sign-up/split" },
			updatePassword: {
				centered: "/auth/samples/update-password/centered",
				split: "/auth/samples/update-password/split",
			},
			resetPassword: { centered: "/auth/samples/reset-password/centered", split: "/auth/samples/reset-password/split" },
			verifyCode: { centered: "/auth/samples/verify-code/centered", split: "/auth/samples/verify-code/split" },
		},
		supabase: {
			callback: { implicit: "/auth/supabase/callback/implicit", pkce: "/auth/supabase/callback/pkce" },
			recoveryLinkSent: "/auth/supabase/recovery-link-sent",
			resetPassword: "/auth/supabase/reset-password",
			signIn: "/auth/supabase/sign-in",
			signOut: "/auth/supabase/sign-out",
			signUp: "/auth/supabase/sign-up",
			signUpConfirm: "/auth/supabase/sign-up-confirm",
			updatePassword: "/auth/supabase/update-password",
		},
	},
	checkout: "/checkout",
	contact: "/contact",
	components: {
		buttons: "/components/buttons",
		charts: "/components/charts",
		colors: "/components/colors",
		detailLists: "/components/detail-lists",
		forms: "/components/forms",
		gridLists: "/components/grid-lists",
		groupedLists: "/components/grouped-lists",
		index: "/components",
		inputs: "/components/inputs",
		modals: "/components/modals",
		quickStats: "/components/quick-stats",
		tables: "/components/tables",
		typography: "/components/typography",
	},
	dashboard: {
		academy: { browse: "/dashboard/academy", details: (courseId) => `/dashboard/academy/courses/${courseId}` },
		applications: "/dashboard/applications",
		analytics: "/dashboard/analytics",
		blank: "/dashboard/blank",
		blog: {
			create: "/dashboard/blog/create",
			details: (postId) => `/dashboard/blog/${postId}`,
			list: "/dashboard/blog",
		},
		calendar: "/dashboard/calendar",
		chat: {
			base: "/dashboard/chat",
			compose: "/dashboard/chat/compose",
			thread: (threadType, threadId) => `/dashboard/chat/${threadType}/${threadId}`,
		},
		configuration: "/dashboard/configuration",
		crypto: "/dashboard/crypto",
		customers: {
			create: "/dashboard/customers/create",
			details: (customerId) => `/dashboard/customers/${customerId}`,
			list: "/dashboard/customers",
		},
		eCommerce: "/dashboard/e-commerce",
		employees: "/dashboard/employees",
		fileStorage: "/dashboard/file-storage",
		i18n: "/dashboard/i18n",
		invoices: {
			create: "/dashboard/invoices/create",
			details: (invoiceId) => `/dashboard/invoices/${invoiceId}`,
			list: "/dashboard/invoices",
		},
		jobs: {
			browse: "/dashboard/jobs",
			create: "/dashboard/jobs/create",
			companies: {
				activity: (companyId) => `/dashboard/jobs/companies/${companyId}/activity`,
				assets: (companyId) => `/dashboard/jobs/companies/${companyId}/assets`,
				overview: (companyId) => `/dashboard/jobs/companies/${companyId}`,
				reviews: (companyId) => `/dashboard/jobs/companies/${companyId}/reviews`,
				team: (companyId) => `/dashboard/jobs/companies/${companyId}/team`,
			},
		},
		logistics: { metrics: "/dashboard/logistics", fleet: "/dashboard/logistics/fleet" },
		mail: {
			list: (label) => `/dashboard/mail/${label}`,
			details: (label, emailId) => `/dashboard/mail/${label}/${emailId}`,
		},
		orders: {
			list: "/dashboard/orders",
			create: "/dashboard/orders/create",
			preview: (orderId) => `/dashboard/orders?previewId=${orderId}`,
			details: (orderId) => `/dashboard/orders/${orderId}`,
		},

		overview: "/dashboard",
		products: {
			list: "/dashboard/products",
			create: "/dashboard/products/create",
			preview: (productId) => `/dashboard/products?previewId=${productId}`,
			details: (productId) => `/dashboard/products/${productId}`,
		},
		pqr: "/dashboard/pqr",
		reports: "/dashboard/reports",
		settings: {
			account: "/dashboard/settings/account",
			billing: "/dashboard/settings/billing",
			integrations: "/dashboard/settings/integrations",
			notifications: "/dashboard/settings/notifications",
			security: "/dashboard/settings/security",
			team: "/dashboard/settings/team",
		},
		social: {
			profile: { timeline: "/dashboard/social/profile", connections: "/dashboard/social/profile/connections" },
			feed: "/dashboard/social/feed",
		},
		tasks: "/dashboard/tasks",
	},
	docs: "https://material-kit-pro-react-docs.devias.io",
	home: "/",
	internalServerError: "/errors/internal-server-error",
	notAuthorized: "/errors/not-authorized",
	notFound: "/errors/not-found",
	pdf: { invoice: (invoiceId) => `/pdf/invoices/${invoiceId}` },
	pricing: "/pricing",
	purchase: "https://mui.com/store/items/devias-kit-pro",
};
