export const paths = {
	auth: {
		auth0: {
			callback: "/auth/auth0/callback",
			profile: "/auth/auth0/profile",
			signIn: "/auth/auth0/sign-in",
			signOut: "/auth/auth0/sign-out",
			signUp: "/auth/auth0/sign-up",
		},
		profile: "/auth/profile",
		resetPassword: "/auth/reset-password",
		signIn: "/auth/sign-in",
		signOut: "/auth/sign-out",
		signUp: "/auth/sign-up",
	},
	dashboard: {
		blank: "/dashboard/blank",
		balance: "/dashboard/balance",
		cash_flow: "/dashboard/cash_flow",
		chat: {
			base: "/dashboard/chat",
			compose: "/dashboard/chat/compose",
			thread: (threadType, threadId) => `/dashboard/chat/${threadType}/${threadId}`,
			preview: (clientId) => `/dashboard/chat?previewId=${clientId}`,
		},
		configuration: {
			permissions: "/dashboard/configuration/permissions",
			amountManagment: "/dashboard/configuration/amount-managment",
			paymentInformation: "/dashboard/configuration/payment-information",
			branchManagment: {
				create: "/dashboard/configuration/branch-managment/create",
				list: "/dashboard/configuration/branch-managment",
			},
		},
		consultations: "/dashboard/consultations",
		customers: {
			create: "/dashboard/customers/create",
			details: (customerId) => `/dashboard/customers/${customerId}`,
			list: "/dashboard/customers",
		},
		i18n: "/dashboard/i18n",
		documents: {
			details: (documentId) => `/dashboard/documents/${documentId}`,
		},
		overview: "/dashboard/overview",
		reports: {
			dailyCashSummary: "/dashboard/reports/daily-cash-summary",
			dailyCashCountByAgent: "/dashboard/reports/daily-cash-count-by-agent",
			activeLoansByStatus: "/dashboard/reports/active-loans-by-status",
			upcomingDueDates: "/dashboard/reports/upcoming-due-dates",
			overdueLoans: "/dashboard/reports/overdue-loans",
			loanHistoryByClient: "/dashboard/reports/loan-history-by-client",
			newClientsByDateRange: "/dashboard/reports/new-clients-by-date-range",
			activeVsInactiveClients: "/dashboard/reports/active-vs-inactive-clients",
			totalLoanAmount: "/dashboard/reports/total-loan-amount",
			totalCollectionReceived: "/dashboard/reports/total-collection-received",
			documentsUploadedByClient: "/dashboard/reports/documents-uploaded-by-client",
			agentActivity: "/dashboard/reports/agent-activity",
			averageApprovalTime: "/dashboard/reports/average-approval-time",
			generalCashFlow: "/dashboard/reports/general-cash-flow",
			transactionDetails: "/dashboard/reports/transaction-details",
			generalStatisticsByBranch: "/dashboard/reports/general-statistics-by-branch",
		},
		requests: {
			create: "/dashboard/requests/create",
			details: (orderId) => `/dashboard/requests/${orderId}`,
			list: "/dashboard/requests",
			preview: (orderId) => `/dashboard/requests?previewId=${orderId}`,
		},
		settings: {
			account: "/dashboard/settings/account",
			billing: "/dashboard/settings/billing",
			integrations: "/dashboard/settings/integrations",
			notifications: "/dashboard/settings/notifications",
			security: "/dashboard/settings/security",
			team: "/dashboard/settings/team",
		},
		users: {
			create: "/dashboard/users/create",
			list: "/dashboard/users",
			details: (userId) => `/dashboard/users/${userId}`,
		},
	},
	dataDeletion: "/data-deletion",
	home: "/",
	internalServerError: "/errors/internal-server-error",
	notAuthorized: "/errors/not-authorized",
	notFound: "/errors/not-found",
	pdf: { invoice: (invoiceId) => `/pdf/invoices/${invoiceId}` },
	pricing: "/pricing",
	privacy: "/privacy",
};
