export const paths = {
	auth: {
		auth0: {
			callback: "/auth/auth0/callback",
			profile: "/auth/auth0/profile",
			signIn: "/auth/auth0/sign-in",
			signOut: "/auth/auth0/sign-out",
			signUp: "/auth/auth0/sign-up",
		},

		profile: "/auth/profile",
		resetPassword: "/auth/reset-password",
		signIn: "/auth/sign-in",
		signOut: "/auth/sign-out",
		signUp: "/auth/sign-up",
	},
	checkout: "/checkout",
	contact: "/contact",
	components: {
		buttons: "/components/buttons",
		charts: "/components/charts",
		colors: "/components/colors",
		detailLists: "/components/detail-lists",
		forms: "/components/forms",
		gridLists: "/components/grid-lists",
		groupedLists: "/components/grouped-lists",
		index: "/components",
		inputs: "/components/inputs",
		modals: "/components/modals",
		quickStats: "/components/quick-stats",
		tables: "/components/tables",
		typography: "/components/typography",
	},
	dashboard: {
		academy: { browse: "/dashboard/academy", details: (courseId) => `/dashboard/academy/courses/${courseId}` },
		analytics: "/dashboard/analytics",
		blank: "/dashboard/blank",
		blog: {
			create: "/dashboard/blog/create",
			details: (postId) => `/dashboard/blog/${postId}`,
			list: "/dashboard/blog",
		},
		cash_flow: "/dashboard/cash_flow",
		calendar: "/dashboard/calendar",
		chat: {
			base: "/dashboard/chat",
			compose: "/dashboard/chat/compose",
			thread: (threadType, threadId) => `/dashboard/chat/${threadType}/${threadId}`,
		},
		configuration: "/dashboard/configuration",
		crypto: "/dashboard/crypto",
		customers: {
			create: "/dashboard/customers/create",
			details: (customerId) => `/dashboard/customers/${customerId}`,
			list: "/dashboard/customers",
		},
		eCommerce: "/dashboard/e-commerce",
		fileStorage: "/dashboard/file-storage",
		i18n: "/dashboard/i18n",
		documents: {
			create: "/dashboard/documents/create",
			details: (documentId) => `/dashboard/documents/${documentId}`,
			list: "/dashboard/documents",
		},
		jobs: {
			browse: "/dashboard/jobs",
			create: "/dashboard/jobs/create",
			companies: {
				activity: (companyId) => `/dashboard/jobs/companies/${companyId}/activity`,
				assets: (companyId) => `/dashboard/jobs/companies/${companyId}/assets`,
				overview: (companyId) => `/dashboard/jobs/companies/${companyId}`,
				reviews: (companyId) => `/dashboard/jobs/companies/${companyId}/reviews`,
				team: (companyId) => `/dashboard/jobs/companies/${companyId}/team`,
			},
		},
		logistics: { metrics: "/dashboard/logistics", fleet: "/dashboard/logistics/fleet" },
		mail: {
			list: (label) => `/dashboard/mail/${label}`,
			details: (label, emailId) => `/dashboard/mail/${label}/${emailId}`,
		},
		overview: "/dashboard/overview",
		products: {
			list: "/dashboard/products",
			create: "/dashboard/products/create",
			preview: (productId) => `/dashboard/products?previewId=${productId}`,
			details: (productId) => `/dashboard/products/${productId}`,
		},
		pqr: "/dashboard/pqr",
		reports: "/dashboard/reports",
		requests: {
			create: "/dashboard/requests/create",
			details: (orderId) => `/dashboard/requests/${orderId}`,
			list: "/dashboard/requests",
			preview: (orderId) => `/dashboard/requests?previewId=${orderId}`,
		},
		settings: {
			account: "/dashboard/settings/account",
			billing: "/dashboard/settings/billing",
			integrations: "/dashboard/settings/integrations",
			notifications: "/dashboard/settings/notifications",
			security: "/dashboard/settings/security",
			team: "/dashboard/settings/team",
		},
		simulator: "/dashboard/simulator-credit",
		social: {
			profile: { timeline: "/dashboard/social/profile", connections: "/dashboard/social/profile/connections" },
			feed: "/dashboard/social/feed",
		},
		tasks: "/dashboard/tasks",
		users: "/dashboard/users",
	},
	dataDeletion: "/data-deletion",
	docs: "https://material-kit-pro-react-docs.devias.io",
	home: "/",
	internalServerError: "/errors/internal-server-error",
	notAuthorized: "/errors/not-authorized",
	notFound: "/errors/not-found",
	pdf: { invoice: (invoiceId) => `/pdf/invoices/${invoiceId}` },
	pricing: "/pricing",
	purchase: "https://mui.com/store/items/devias-kit-pro",
	privacy: "/privacy",
};
